# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riakBd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='name')),
                ('locacao', models.CharField(max_length=150, verbose_name='location')),
                ('profissao', models.CharField(max_length=150, verbose_name='role')),
                ('apelido', models.CharField(max_length=150, verbose_name='fulname')),
            ],
        ),
    ]
